# Generated by Django 5.2.10 on 2026-07-27 22:04

import api.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Mojo and Co', max_length=120)),
                ('contact_phone', models.CharField(default='07743 525 386', max_length=20)),
                ('contact_email', models.EmailField(default='info@mojoandco.uk', max_length=254)),
                ('invoicing_visible_to_clients', models.BooleanField(default=False, help_text='Invoicing starts hidden from clients; flip this on when ready to share it.')),
                ('booking_slot_buffer_minutes', models.PositiveIntegerField(default=0, help_text='Extra minutes added after each appointment when suggesting slots.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'App settings',
            },
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('coat_type', models.CharField(blank=True, help_text='e.g. double, curly, wire, smooth.', max_length=60)),
                ('avg_groom_minutes', models.PositiveIntegerField(help_text='Typical full groom time in minutes.')),
                ('avg_price', models.DecimalField(decimal_places=2, help_text='Typical full groom price in GBP.', max_digits=7)),
                ('avg_schedule_weeks', models.PositiveIntegerField(help_text='Typical interval between grooms, in weeks.')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClosureDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('uid', models.CharField(help_text='Asset reference, e.g. BLADE-07.', max_length=32, unique=True)),
                ('last_sharpened', models.DateField(blank=True, null=True)),
                ('pat_tested', models.BooleanField(default=False)),
                ('pat_tested_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Equipment',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], unique=True)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Opening hours',
                'ordering': ['weekday'],
            },
        ),
        migrations.CreateModel(
            name='TemperamentLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperament', models.CharField(choices=[('EASY', 'Easy'), ('FIDGETY', 'Fidgety / bitey'), ('FEISTY', 'Feisty / hard')], max_length=10, unique=True)),
                ('max_per_day', models.PositiveIntegerField(blank=True, help_text='Blank means no limit.', null=True)),
            ],
            options={
                'ordering': ['temperament'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(help_text="Jess's own reference for this client, e.g. MOJO-014. Editable by staff.", max_length=32, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('postcode', models.CharField(blank=True, max_length=10)),
                ('chatty', models.BooleanField(default=False, help_text='This owner likes a chat — allow extra time at drop-off/collection. Hidden from clients.')),
                ('leaflet_received', models.BooleanField(default=False, help_text='Has been given the welcome leaflet.')),
                ('notes', models.TextField(blank=True, help_text='Private staff notes about this client. Hidden from clients.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='ClientClaimRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_name', models.CharField(max_length=200)),
                ('claimed_email', models.EmailField(max_length=254)),
                ('claimed_postcode', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_client', models.ForeignKey(blank=True, help_text='Best server-side match, for staff to confirm or override.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_requests', to='api.client')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_claims', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed_other', models.CharField(blank=True, help_text='Free text when the breed is a cross or not on the list.', max_length=120)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('is_neutered', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='dog_profiles/')),
                ('temperament', models.CharField(choices=[('EASY', 'Easy'), ('FIDGETY', 'Fidgety / bitey'), ('FEISTY', 'Feisty / hard')], default='EASY', help_text='Handling difficulty. Drives the per-day booking limit. Hidden from clients.', max_length=10)),
                ('temperament_notes', models.TextField(blank=True, help_text='How to handle this dog. Hidden from clients.')),
                ('groom_minutes', models.PositiveIntegerField(blank=True, help_text='Overrides the breed average. Blank = use the breed default.', null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Overrides the breed average price. Blank = use the breed default.', max_digits=7, null=True)),
                ('schedule_weeks', models.PositiveIntegerField(blank=True, help_text='Overrides the breed average grooming interval. Blank = use the breed default.', null=True)),
                ('pref_body', models.TextField(blank=True, verbose_name='Body')),
                ('pref_feet', models.TextField(blank=True, verbose_name='Feet shape')),
                ('pref_tail', models.TextField(blank=True, verbose_name='Tail')),
                ('pref_face', models.TextField(blank=True, verbose_name='Face')),
                ('pref_ears', models.TextField(blank=True, verbose_name='Ears')),
                ('pref_skirt', models.TextField(blank=True, verbose_name='Skirt')),
                ('medical_notes', models.TextField(blank=True)),
                ('vet', models.TextField(blank=True, help_text='Practice name, address and phone number.')),
                ('general_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dogs', to='api.breed')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to='api.client')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookingSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_weeks', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Blank = runs indefinitely.', null=True)),
                ('preferred_time', models.TimeField()),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_series', to=settings.AUTH_USER_MODEL)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_series', to='api.dog')),
            ],
            options={
                'verbose_name_plural': 'Booking series',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('booking_type', models.CharField(choices=[('FIRST_GROOM', 'First groom'), ('ADHOC', 'Ad hoc'), ('SCHEDULED', 'Scheduled')], default='ADHOC', max_length=12)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('BOOKED', 'Booked'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No show')], default='BOOKED', max_length=12)),
                ('price_quoted', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='api.bookingseries')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='api.dog')),
            ],
            options={
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='DogPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dog_photos/')),
                ('taken_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the photo was taken — drives date sorting.')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='api.appointment')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.dog')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dog_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-taken_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GroomSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('applied_to_dog_at', models.DateTimeField(blank=True, help_text="Set when this session's total was written to the dog's default groom time.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groom_sessions', to='api.appointment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groom_sessions', to=settings.AUTH_USER_MODEL)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groom_sessions', to='api.dog')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='IntakeInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(default=api.models.generate_intake_token, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, help_text='Set when inviting an existing client to complete their details.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intake_invites', to='api.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntakeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('postcode', models.CharField(blank=True, max_length=10)),
                ('dogs', models.JSONField(default=list, help_text='Submitted dogs: name, breed, dob, sex, preferences and problem areas.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_submissions', to='api.client')),
                ('invite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='api.intakeinvite')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_intakes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, unique=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PAID', 'Paid'), ('VOID', 'Void')], default='DRAFT', max_length=6)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='api.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='api.appointment')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='api.invoice')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('paid_at', models.DateField(default=django.utils.timezone.localdate)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('BANK', 'Bank transfer'), ('OTHER', 'Other')], default='CARD', max_length=6)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.invoice')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paid_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PhaseTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('PREP', 'Prep'), ('WASH', 'Wash'), ('DRY', 'Dry'), ('CLIP', 'Clip'), ('STRIP', 'Strip')], max_length=10)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('entered_manually', models.BooleanField(default=False, help_text='True when the duration was typed in rather than timed.')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timings', to='api.groomsession')),
            ],
            options={
                'ordering': ['session', 'phase'],
            },
        ),
        migrations.CreateModel(
            name='ProblemArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_cells', models.JSONField(default=list, help_text='Selected silhouette cells, e.g. ["r3c5", "r3c6"].')),
                ('reason', models.TextField(help_text='Why this area is marked — sore, matted, dislikes being touched, etc.')),
                ('source', models.CharField(choices=[('STAFF', 'Added by staff'), ('INTAKE', 'From intake form')], default='STAFF', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problem_areas', to=settings.AUTH_USER_MODEL)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_areas', to='api.dog')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('is_done', models.BooleanField(default=False)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['is_done', 'sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='staff_photos/')),
                ('can_manage_clients', models.BooleanField(default=False, help_text='Create and edit client and dog records.')),
                ('can_manage_bookings', models.BooleanField(default=False, help_text='Create, move and cancel appointments.')),
                ('can_manage_invoices', models.BooleanField(default=False, help_text='Raise invoices and record payments.')),
                ('can_manage_equipment', models.BooleanField(default=False, help_text='Maintain the equipment register.')),
                ('can_manage_settings', models.BooleanField(default=False, help_text='Change opening hours, temperament limits and app settings.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['uid'], name='api_client_uid_a30914_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['phone'], name='api_client_phone_dfeac6_idx'),
        ),
        migrations.AddIndex(
            model_name='dog',
            index=models.Index(fields=['name'], name='api_dog_name_cad3b4_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['start_at'], name='api_appoint_start_a_ca3707_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='api_appoint_status_323c16_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='phasetiming',
            unique_together={('session', 'phase')},
        ),
    ]
