# Generated by Django 5.2.10 on 2026-08-01 07:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_passwordresettoken_passwordresetrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='dog',
            name='allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='colour',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='dog',
            name='last_vet_visit',
            field=models.TextField(blank=True, help_text='What the last vet trip was for.'),
        ),
        migrations.AddField(
            model_name='dog',
            name='medical_issues',
            field=models.TextField(blank=True, verbose_name='Known medical issues'),
        ),
        migrations.AddField(
            model_name='dog',
            name='medications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='microchip_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='dog',
            name='owner_grooming',
            field=models.TextField(blank=True, help_text='What the owner does themselves between grooms, and how often.'),
        ),
        migrations.AddField(
            model_name='dog',
            name='vaccinations',
            field=models.TextField(blank=True, help_text='Which vaccinations, and when.'),
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='consents',
            field=models.JSONField(default=dict, help_text='Which disclaimers were agreed, by kind.'),
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='intakesubmission',
            name='signature',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('policies', 'I have read and agree to the grooming policies and the privacy policy'), ('accuracy', 'These details are right, and I will tell you if anything changes'), ('matting', 'If my dog is badly matted, the coat may have to come off entirely'), ('restraint', 'A collar or muzzle may be used if my dog will not settle'), ('vet', 'In an emergency a vet will be contacted, and treatment is at my cost'), ('photos', 'Photos of my dog may be used on the website and social media')], max_length=20)),
                ('agreed', models.BooleanField()),
                ('signed_name', models.CharField(help_text='Typed by the client on the form — the web equivalent of a signature.', max_length=120)),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When it was agreed. Defaults to now, but a card signed on paper keeps its own date.')),
                ('wording', models.TextField(blank=True, help_text='The text as it was shown at the time, so a later rewording cannot rewrite history.')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='api.client')),
            ],
            options={
                'ordering': ['-signed_at'],
                'indexes': [models.Index(fields=['client', 'kind'], name='api_consent_client__472ce7_idx')],
            },
        ),
    ]
