# Generated by Django 5.2.10 on 2026-08-01 08:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_client_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='service_type',
            field=models.CharField(choices=[('GROOM', 'Groom'), ('NAILS', 'Nails, fleas or ticks')], default='GROOM', max_length=10),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='nail_visit_minutes',
            field=models.PositiveIntegerField(default=20, help_text='How long to block out for a nails, flea or tick visit.'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='nail_visit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='What a nails, flea or tick visit costs. Not from the breed price list.', max_digits=7),
        ),
        migrations.AddField(
            model_name='groomsession',
            name='bathed_well_behaved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groomsession',
            name='equipment_used',
            field=models.ManyToManyField(blank=True, related_name='groom_sessions', to='api.equipment'),
        ),
        migrations.AddField(
            model_name='groomsession',
            name='final_body',
            field=models.TextField(blank=True, verbose_name='Final body trim'),
        ),
        migrations.AddField(
            model_name='groomsession',
            name='final_feet',
            field=models.TextField(blank=True, verbose_name='Final feet shape'),
        ),
        migrations.AddField(
            model_name='groomsession',
            name='final_tail',
            field=models.TextField(blank=True, verbose_name='Final tail'),
        ),
        migrations.AddField(
            model_name='groomsession',
            name='fleas_treated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groomsession',
            name='health_check_notes',
            field=models.TextField(blank=True, help_text='Anything found on the health check.'),
        ),
        migrations.AddField(
            model_name='groomsession',
            name='high_velocity_dryer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groomsession',
            name='matting_armpits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groomsession',
            name='matting_ears',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groomsession',
            name='matting_elsewhere',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groomsession',
            name='matting_notes',
            field=models.TextField(blank=True, help_text='Where else, and how bad.'),
        ),
        migrations.AddField(
            model_name='groomsession',
            name='matting_paws',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groomsession',
            name='nails_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groomsession',
            name='recorded_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='How long the visit took, when the timer was not used. Overrides the phase total.', null=True),
        ),
        migrations.AddField(
            model_name='groomsession',
            name='sensitive_notes',
            field=models.TextField(blank=True, help_text="Anywhere the dog didn't want to be touched, was fidgety or sensitive."),
        ),
        migrations.AddField(
            model_name='groomsession',
            name='shampoo_used',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='groomsession',
            name='temperament_observed',
            field=models.CharField(blank=True, choices=[('EASY', 'Easy'), ('FIDGETY', 'Fidgety / bitey'), ('FEISTY', 'Feisty / hard')], max_length=10),
        ),
        migrations.AddField(
            model_name='groomsession',
            name='ticks_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groomsession',
            name='visit_type',
            field=models.CharField(choices=[('GROOM', 'Groom'), ('NAILS', 'Nails, fleas or ticks')], default='GROOM', max_length=10),
        ),
        migrations.AlterField(
            model_name='groomsession',
            name='notes',
            field=models.TextField(blank=True, help_text='Anything to note about the visit.'),
        ),
    ]
