# Generated by Django 5.2.10 on 2026-08-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_appointment_service_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='nail_visit_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='How long to block out for a nails, flea or tick visit. Blank until set.', null=True),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='nail_visit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='What a nails, flea or tick visit costs. Not from the breed price list.', max_digits=7, null=True),
        ),
    ]
