# Generated by Django 5.2.10 on 2026-08-01 18:29

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_client_change_requests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DogDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=api.models.private_storage, upload_to=api.models.document_upload_path)),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('INTAKE_FORM', 'Intake form'), ('VACCINATION', 'Vaccination record'), ('VET', 'Vet letter'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('visible_to_client', models.BooleanField(default=True, help_text="Whether the dog's owner can see and download this. On by default because the point of the feature is letting them see their own form — turn it off for anything you are filing for yourself.")),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.dog')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dog_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
