# Generated by Django 5.2.10 on 2026-08-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_appointmentchangerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
    ]
