# Generated by Django 5.2.10 on 2026-08-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='average_groom_minutes',
            field=models.PositiveIntegerField(blank=True, editable=False, help_text='Worked out from past grooms. Not edited by hand.', null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='requires_restraint',
            field=models.BooleanField(default=False, help_text='This dog needs a collar or muzzle to be groomed safely. Hidden from clients.', verbose_name='Restraints required'),
        ),
        migrations.AddField(
            model_name='groomsession',
            name='final_face',
            field=models.TextField(blank=True, verbose_name='Final face shape'),
        ),
    ]
