# Generated by Django 5.2.10 on 2026-08-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_dog_average_groom_minutes_dog_requires_restraint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=6),
        ),
        migrations.AddField(
            model_name='breed',
            name='chest_shape',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='breed',
            name='coat_colours',
            field=models.TextField(blank=True, verbose_name='Colours of coat'),
        ),
        migrations.AddField(
            model_name='breed',
            name='common_ailments',
            field=models.TextField(blank=True, help_text='What this breed tends to suffer from. Link the detail under Medical notes.'),
        ),
        migrations.AddField(
            model_name='breed',
            name='ear_shape',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='breed',
            name='groom_style_body',
            field=models.TextField(blank=True, verbose_name='Groom style — body'),
        ),
        migrations.AddField(
            model_name='breed',
            name='groom_style_ears',
            field=models.TextField(blank=True, verbose_name='Groom style — ears'),
        ),
        migrations.AddField(
            model_name='breed',
            name='groom_style_feet',
            field=models.TextField(blank=True, verbose_name='Groom style — feet'),
        ),
        migrations.AddField(
            model_name='breed',
            name='groom_style_head',
            field=models.TextField(blank=True, verbose_name='Groom style — head'),
        ),
        migrations.AddField(
            model_name='breed',
            name='groom_style_tail',
            field=models.TextField(blank=True, verbose_name='Groom style — tail'),
        ),
        migrations.AddField(
            model_name='breed',
            name='grooming_technique',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='breed',
            name='head_shape',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='breed',
            name='head_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='breed',
            name='height_max_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Height to (cm)'),
        ),
        migrations.AddField(
            model_name='breed',
            name='height_min_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Height from (cm)'),
        ),
        migrations.AddField(
            model_name='breed',
            name='kennel_club_group',
            field=models.CharField(blank=True, choices=[('GUNDOG', 'Gundog'), ('HOUND', 'Hound'), ('PASTORAL', 'Pastoral'), ('TERRIER', 'Terrier'), ('TOY', 'Toy'), ('UTILITY', 'Utility'), ('WORKING', 'Working')], max_length=10, verbose_name='UK Kennel Club group'),
        ),
        migrations.AddField(
            model_name='breed',
            name='life_span_max_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='breed',
            name='life_span_min_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='breed',
            name='original_purpose',
            field=models.TextField(blank=True, help_text='What the breed was originally bred to do.'),
        ),
        migrations.AddField(
            model_name='breed',
            name='size_band',
            field=models.CharField(blank=True, choices=[('toy', 'Toy'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('colossal', 'Colossal (45kg and over)')], help_text='The other axis of the price grid.', max_length=10),
        ),
        migrations.AddField(
            model_name='breed',
            name='weight_max_kg',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='breed',
            name='weight_min_kg',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='breed',
            name='coat_type',
            field=models.CharField(blank=True, choices=[('smooth', 'Smooth'), ('short double', 'Short double'), ('long double', 'Long double'), ('curly', 'Curly'), ('wire', 'Wire'), ('hairless', 'Hairless'), ('corded', 'Corded'), ('silky', 'Silky / drop')], help_text='One axis of the price grid. The last three are not on it.', max_length=60),
        ),
        migrations.CreateModel(
            name='MedicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('kind', models.CharField(choices=[('AILMENT', 'Condition or ailment'), ('FIRST_AID', 'First aid'), ('GROOMING_CARE', 'Care when grooming')], default='AILMENT', max_length=15)),
                ('what_it_means', models.TextField(blank=True, help_text='Plain-English explanation of the term.')),
                ('grooming_care', models.TextField(blank=True, help_text='What to watch for, or do differently, when grooming a dog with this.')),
                ('first_aid', models.TextField(blank=True, help_text='What to do if it happens in the salon.')),
                ('source', models.CharField(blank=True, help_text='Where this came from — your vet, a course, a book. Left blank it is nobody in particular.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breeds', models.ManyToManyField(blank=True, help_text='Breeds this is common in. Optional — plenty of these are not breed-specific.', related_name='medical_notes', to='api.breed')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
